# Generated by Django 6.0.2 on 2026-02-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='username',
            field=models.CharField(default='default_username', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='regularuser',
            name='username',
            field=models.CharField(default='default_username', max_length=100, unique=True),
        ),
    ]
