# Generated by Django 6.0.2 on 2026-02-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_adminuser_username_regularuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='regularuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
