# Generated by Django 6.0.2 on 2026-02-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_state'),
        ('users', '0004_user_delete_adminuser_delete_regularuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_ids',
            field=models.ManyToManyField(blank=True, related_name='users', to='devices.device'),
        ),
    ]
