# Generated by Django 6.0.2 on 2026-02-26 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_device_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='device_ids',
        ),
    ]
