# Generated by Django 6.0.2 on 2026-02-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_state'),
        ('users', '0006_remove_user_device_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_ids',
            field=models.ManyToManyField(blank=True, related_name='users', to='devices.device'),
        ),
    ]
