# Generated by Django 6.0.2 on 2026-02-26 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_owner'),
        ('telemerty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='telemerty.devicetelemetry'),
        ),
    ]
