# Generated by Django 6.0.2 on 2026-02-27 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='state',
        ),
    ]
