# Generated by Django 6.0.2 on 2026-02-27 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_remove_device_state'),
        ('telemerty', '0004_alter_devicetelemetry_device_alter_alertrule_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='telemetry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_one_to_one', to='telemerty.devicetelemetry'),
        ),
    ]
