# Generated by Django 6.0.2 on 2026-02-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemerty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetelemetry',
            name='cpu',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='devicetelemetry',
            name='memory',
            field=models.FloatField(default=0.0),
        ),
    ]
