# Generated by Django 6.0.2 on 2026-02-26 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_state'),
        ('telemerty', '0002_alter_devicetelemetry_cpu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('CPU', 'Cpu'), ('MEMORY', 'Memory'), ('TEMPERATURE', 'Temperature'), ('OFFLINE', 'Offline')], max_length=20)),
                ('operator', models.CharField(blank=True, choices=[('>', 'Gt'), ('<', 'Lt'), ('>=', 'Gte'), ('<=', 'Lte'), ('=', 'Eq')], max_length=5, null=True)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('offline_minutes', models.IntegerField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('state', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemerty.alertrule')),
            ],
        ),
    ]
