# Generated by Django 6.0.2 on 2026-02-27 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_remove_device_state'),
        ('telemerty', '0003_alertrule_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetelemetry',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_telemetry', to='devices.device'),
        ),
        migrations.AlterModelTable(
            name='alertrule',
            table='alert_rule',
        ),
        migrations.AlterModelTable(
            name='devicetelemetry',
            table='device_telemetry',
        ),
    ]
